
GET http://localhost:8080/demo/all

###

POST http://localhost:8080/demo/add
Content-Type: application/x-www-form-urlencoded

pet=Cloe
&raza=GranDanes
&duenio=David
###

GET http://localhost:8080/demo/ver/2

###

PUT http://localhost:8080/demo/edit
Content-Type: application/x-www-form-urlencoded

id=102
&pet=chato
&raza=Pequines
&duenio=Joan

###

DELETE http://localhost:8080/demo/del
Content-Type: application/x-www-form-urlencoded

id=152

###

GET http://localhost:8080/demo/get/report

